/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface GeoJSONFeature {
  type: "Feature";
  id?: number | string;
  properties: null | {
    [k: string]: unknown;
  };
  geometry:
    | null
    | GeoJSONPoint
    | GeoJSONLineString
    | GeoJSONPolygon
    | GeoJSONMultiPoint
    | GeoJSONMultiLineString
    | GeoJSONMultiPolygon
    | GeoJSONGeometryCollection;
  bbox?: [number, number, number, number, ...number[]];
  [k: string]: unknown;
}
export interface GeoJSONPoint {
  type: "Point";
  coordinates: [number, number, ...number[]];
  bbox?: [number, number, number, number, ...number[]];
  [k: string]: unknown;
}
export interface GeoJSONLineString {
  type: "LineString";
  coordinates: [
    [number, number, ...number[]],
    [number, number, ...number[]],
    ...[number, number, ...number[]][]
  ];
  bbox?: [number, number, number, number, ...number[]];
  [k: string]: unknown;
}
export interface GeoJSONPolygon {
  type: "Polygon";
  coordinates: [
    [number, number, ...number[]],
    [number, number, ...number[]],
    [number, number, ...number[]],
    [number, number, ...number[]],
    ...[number, number, ...number[]][]
  ][];
  bbox?: [number, number, number, number, ...number[]];
  [k: string]: unknown;
}
export interface GeoJSONMultiPoint {
  type: "MultiPoint";
  coordinates: [number, number, ...number[]][];
  bbox?: [number, number, number, number, ...number[]];
  [k: string]: unknown;
}
export interface GeoJSONMultiLineString {
  type: "MultiLineString";
  coordinates: [
    [number, number, ...number[]],
    [number, number, ...number[]],
    ...[number, number, ...number[]][]
  ][];
  bbox?: [number, number, number, number, ...number[]];
  [k: string]: unknown;
}
export interface GeoJSONMultiPolygon {
  type: "MultiPolygon";
  coordinates: [
    [number, number, ...number[]],
    [number, number, ...number[]],
    [number, number, ...number[]],
    [number, number, ...number[]],
    ...[number, number, ...number[]][]
  ][][];
  bbox?: [number, number, number, number, ...number[]];
  [k: string]: unknown;
}
export interface GeoJSONGeometryCollection {
  type: "GeometryCollection";
  geometries: (
    | GeoJSONPoint1
    | GeoJSONLineString1
    | GeoJSONPolygon1
    | GeoJSONMultiPoint1
    | GeoJSONMultiLineString1
    | GeoJSONMultiPolygon1
  )[];
  bbox?: [number, number, number, number, ...number[]];
  [k: string]: unknown;
}
export interface GeoJSONPoint1 {
  type: "Point";
  coordinates: [number, number, ...number[]];
  bbox?: [number, number, number, number, ...number[]];
  [k: string]: unknown;
}
export interface GeoJSONLineString1 {
  type: "LineString";
  coordinates: [
    [number, number, ...number[]],
    [number, number, ...number[]],
    ...[number, number, ...number[]][]
  ];
  bbox?: [number, number, number, number, ...number[]];
  [k: string]: unknown;
}
export interface GeoJSONPolygon1 {
  type: "Polygon";
  coordinates: [
    [number, number, ...number[]],
    [number, number, ...number[]],
    [number, number, ...number[]],
    [number, number, ...number[]],
    ...[number, number, ...number[]][]
  ][];
  bbox?: [number, number, number, number, ...number[]];
  [k: string]: unknown;
}
export interface GeoJSONMultiPoint1 {
  type: "MultiPoint";
  coordinates: [number, number, ...number[]][];
  bbox?: [number, number, number, number, ...number[]];
  [k: string]: unknown;
}
export interface GeoJSONMultiLineString1 {
  type: "MultiLineString";
  coordinates: [
    [number, number, ...number[]],
    [number, number, ...number[]],
    ...[number, number, ...number[]][]
  ][];
  bbox?: [number, number, number, number, ...number[]];
  [k: string]: unknown;
}
export interface GeoJSONMultiPolygon1 {
  type: "MultiPolygon";
  coordinates: [
    [number, number, ...number[]],
    [number, number, ...number[]],
    [number, number, ...number[]],
    [number, number, ...number[]],
    ...[number, number, ...number[]][]
  ][][];
  bbox?: [number, number, number, number, ...number[]];
  [k: string]: unknown;
}
